// @ts-nocheck — generated by scripts/gen-lohnsteuer.py from Lohnsteuer2026.xml (md5 ce4e539bc56ff5605ec01ef94a12664a); do not edit
// The German payroll tax plan (Lohnsteuer2026) exactly as the Finance Ministry publishes it.
/* Exactly the part of Java's BigDecimal that the Finance Ministry's payroll-tax plan
   (Programmablaufplan, PAP) is written in — so the generated code (lohnsteuer2026.gen.ts)
   computes digit for digit what every German payroll program computes. A number is an
   integer `u` (unscaled) with `scale` decimals: 12.50 = { u: 1250n, scale: 2 }.
   No floating point anywhere once a value is in. */

const P10 = (n: number) => 10n ** BigInt(n)

export class BigDecimal {
  readonly u: bigint
  readonly scale: number
  constructor(u: bigint, scale: number) { this.u = u; this.scale = scale }

  static readonly ROUND_UP = 0     // away from zero
  static readonly ROUND_DOWN = 1   // towards zero
  static readonly ZERO = new BigDecimal(0n, 0)
  static readonly ONE = new BigDecimal(1n, 0)
  static readonly TEN = new BigDecimal(10n, 0)

  /* Java's valueOf(double) goes through Double.toString, valueOf(long) is exact; for the
     literals in the PAP both are the shortest decimal that names the number */
  static valueOf(v: number | bigint | string | BigDecimal): BigDecimal {
    if (v instanceof BigDecimal) return v
    if (typeof v === 'string') return BigDecimal.parse(v)
    if (typeof v === 'bigint') return new BigDecimal(v, 0)
    if (!Number.isFinite(v)) throw new Error('BigDecimal.valueOf: not a number')
    if (Number.isInteger(v) && Math.abs(v) <= Number.MAX_SAFE_INTEGER) return new BigDecimal(BigInt(v), 0)
    return BigDecimal.parse(String(v))
  }

  static parse(s: string): BigDecimal {
    const m = /^([+-]?)(\d*)(?:\.(\d*))?(?:e([+-]?\d+))?$/i.exec(s.trim())
    if (!m) throw new Error(`BigDecimal.parse: ${s}`)
    const frac = m[3] || ''
    let scale = frac.length - (m[4] ? parseInt(m[4], 10) : 0)
    let u = BigInt((m[2] || '0') + frac)
    if (scale < 0) { u *= P10(-scale); scale = 0 }
    return new BigDecimal(m[1] === '-' ? -u : u, scale)
  }

  private at(scale: number): bigint {
    return scale >= this.scale ? this.u * P10(scale - this.scale) : this.u / P10(this.scale - scale)
  }

  add(o: BigDecimal): BigDecimal { const s = Math.max(this.scale, o.scale); return new BigDecimal(this.at(s) + o.at(s), s) }
  subtract(o: BigDecimal): BigDecimal { const s = Math.max(this.scale, o.scale); return new BigDecimal(this.at(s) - o.at(s), s) }
  multiply(o: BigDecimal): BigDecimal { return new BigDecimal(this.u * o.u, this.scale + o.scale) }

  compareTo(o: BigDecimal): -1 | 0 | 1 {
    const s = Math.max(this.scale, o.scale)
    const a = this.at(s), b = o.at(s)
    return a < b ? -1 : a > b ? 1 : 0
  }

  setScale(scale: number, mode: number): BigDecimal {
    if (scale >= this.scale) return new BigDecimal(this.at(scale), scale)
    const d = P10(this.scale - scale)
    const q = this.u / d, r = this.u % d                      // bigint division truncates towards zero
    return new BigDecimal(mode === BigDecimal.ROUND_UP && r !== 0n ? q + (this.u < 0n ? -1n : 1n) : q, scale)
  }

  /* divide(x, scale, mode) rounds to that scale; divide(x) must be exact, as in Java
     (which throws on a quotient that never ends) */
  divide(o: BigDecimal, scale?: number, mode?: number): BigDecimal {
    if (o.u === 0n) throw new Error('BigDecimal.divide: by zero')
    if (scale === undefined) {
      // the smallest number of decimals that holds the quotient exactly (every later rounding
      // in the PAP is explicit, so only the value matters, not how many trailing zeros it keeps)
      for (let s = 0; s <= 40; s++) {
        const num = this.u * P10(s + o.scale), den = o.u * P10(this.scale)
        if (num % den === 0n) return new BigDecimal(num / den, s)
      }
      throw new Error('BigDecimal.divide: non-terminating decimal expansion')
    }
    // the exact quotient at scale+1 decides nothing on its own; do it on the integers
    const num = this.u * P10(scale + o.scale), den = o.u * P10(this.scale)
    const q = num / den, r = num % den
    return new BigDecimal(mode === BigDecimal.ROUND_UP && r !== 0n ? q + ((num < 0n) !== (den < 0n) ? -1n : 1n) : q, scale)
  }

  longValue(): number { return Number(this.at(0)) }
  toNumber(): number { return Number(this.u) / Number(P10(this.scale)) }
  toString(): string {
    const neg = this.u < 0n, a = (neg ? -this.u : this.u).toString().padStart(this.scale + 1, '0')
    return (neg ? '-' : '') + (this.scale ? `${a.slice(0, -this.scale)}.${a.slice(-this.scale)}` : a)
  }
}


const TAB1: any = [BigDecimal.ZERO, BigDecimal.valueOf(0.4), BigDecimal.valueOf(0.384), BigDecimal.valueOf(0.368), BigDecimal.valueOf(0.352), BigDecimal.valueOf(0.336), BigDecimal.valueOf(0.32), BigDecimal.valueOf(0.304), BigDecimal.valueOf(0.288), BigDecimal.valueOf(0.272), BigDecimal.valueOf(0.256), BigDecimal.valueOf(0.24), BigDecimal.valueOf(0.224), BigDecimal.valueOf(0.208), BigDecimal.valueOf(0.192), BigDecimal.valueOf(0.176), BigDecimal.valueOf(0.16), BigDecimal.valueOf(0.152), BigDecimal.valueOf(0.144), BigDecimal.valueOf(0.14), BigDecimal.valueOf(0.136), BigDecimal.valueOf(0.132), BigDecimal.valueOf(0.128), BigDecimal.valueOf(0.124), BigDecimal.valueOf(0.12), BigDecimal.valueOf(0.116), BigDecimal.valueOf(0.112), BigDecimal.valueOf(0.108), BigDecimal.valueOf(0.104), BigDecimal.valueOf(0.1), BigDecimal.valueOf(0.096), BigDecimal.valueOf(0.092), BigDecimal.valueOf(0.088), BigDecimal.valueOf(0.084), BigDecimal.valueOf(0.08), BigDecimal.valueOf(0.076), BigDecimal.valueOf(0.072), BigDecimal.valueOf(0.068), BigDecimal.valueOf(0.064), BigDecimal.valueOf(0.06), BigDecimal.valueOf(0.056), BigDecimal.valueOf(0.052), BigDecimal.valueOf(0.048), BigDecimal.valueOf(0.044), BigDecimal.valueOf(0.04), BigDecimal.valueOf(0.036), BigDecimal.valueOf(0.032), BigDecimal.valueOf(0.028), BigDecimal.valueOf(0.024), BigDecimal.valueOf(0.02), BigDecimal.valueOf(0.016), BigDecimal.valueOf(0.012), BigDecimal.valueOf(0.008), BigDecimal.valueOf(0.004), BigDecimal.valueOf(0)]
const TAB2: any = [BigDecimal.ZERO, BigDecimal.valueOf(3000), BigDecimal.valueOf(2880), BigDecimal.valueOf(2760), BigDecimal.valueOf(2640), BigDecimal.valueOf(2520), BigDecimal.valueOf(2400), BigDecimal.valueOf(2280), BigDecimal.valueOf(2160), BigDecimal.valueOf(2040), BigDecimal.valueOf(1920), BigDecimal.valueOf(1800), BigDecimal.valueOf(1680), BigDecimal.valueOf(1560), BigDecimal.valueOf(1440), BigDecimal.valueOf(1320), BigDecimal.valueOf(1200), BigDecimal.valueOf(1140), BigDecimal.valueOf(1080), BigDecimal.valueOf(1050), BigDecimal.valueOf(1020), BigDecimal.valueOf(990), BigDecimal.valueOf(960), BigDecimal.valueOf(930), BigDecimal.valueOf(900), BigDecimal.valueOf(870), BigDecimal.valueOf(840), BigDecimal.valueOf(810), BigDecimal.valueOf(780), BigDecimal.valueOf(750), BigDecimal.valueOf(720), BigDecimal.valueOf(690), BigDecimal.valueOf(660), BigDecimal.valueOf(630), BigDecimal.valueOf(600), BigDecimal.valueOf(570), BigDecimal.valueOf(540), BigDecimal.valueOf(510), BigDecimal.valueOf(480), BigDecimal.valueOf(450), BigDecimal.valueOf(420), BigDecimal.valueOf(390), BigDecimal.valueOf(360), BigDecimal.valueOf(330), BigDecimal.valueOf(300), BigDecimal.valueOf(270), BigDecimal.valueOf(240), BigDecimal.valueOf(210), BigDecimal.valueOf(180), BigDecimal.valueOf(150), BigDecimal.valueOf(120), BigDecimal.valueOf(90), BigDecimal.valueOf(60), BigDecimal.valueOf(30), BigDecimal.valueOf(0) ]
const TAB3: any = [BigDecimal.ZERO, BigDecimal.valueOf(900), BigDecimal.valueOf(864), BigDecimal.valueOf(828), BigDecimal.valueOf(792), BigDecimal.valueOf(756), BigDecimal.valueOf(720), BigDecimal.valueOf(684), BigDecimal.valueOf(648), BigDecimal.valueOf(612), BigDecimal.valueOf(576), BigDecimal.valueOf(540), BigDecimal.valueOf(504), BigDecimal.valueOf(468), BigDecimal.valueOf(432), BigDecimal.valueOf(396), BigDecimal.valueOf(360), BigDecimal.valueOf(342), BigDecimal.valueOf(324), BigDecimal.valueOf(315), BigDecimal.valueOf(306), BigDecimal.valueOf(297), BigDecimal.valueOf(288), BigDecimal.valueOf(279), BigDecimal.valueOf(270), BigDecimal.valueOf(261), BigDecimal.valueOf(252), BigDecimal.valueOf(243), BigDecimal.valueOf(234), BigDecimal.valueOf(225), BigDecimal.valueOf(216), BigDecimal.valueOf(207), BigDecimal.valueOf(198), BigDecimal.valueOf(189), BigDecimal.valueOf(180), BigDecimal.valueOf(171), BigDecimal.valueOf(162), BigDecimal.valueOf(153), BigDecimal.valueOf(144), BigDecimal.valueOf(135), BigDecimal.valueOf(126), BigDecimal.valueOf(117), BigDecimal.valueOf(108), BigDecimal.valueOf(99), BigDecimal.valueOf(90), BigDecimal.valueOf(81), BigDecimal.valueOf(72), BigDecimal.valueOf(63), BigDecimal.valueOf(54), BigDecimal.valueOf(45), BigDecimal.valueOf(36), BigDecimal.valueOf(27), BigDecimal.valueOf(18), BigDecimal.valueOf(9), BigDecimal.valueOf(0)]
const TAB4: any = [BigDecimal.ZERO, BigDecimal.valueOf(0.4), BigDecimal.valueOf(0.384), BigDecimal.valueOf(0.368), BigDecimal.valueOf(0.352), BigDecimal.valueOf(0.336), BigDecimal.valueOf(0.32), BigDecimal.valueOf(0.304), BigDecimal.valueOf(0.288), BigDecimal.valueOf(0.272), BigDecimal.valueOf(0.256), BigDecimal.valueOf(0.24), BigDecimal.valueOf(0.224), BigDecimal.valueOf(0.208), BigDecimal.valueOf(0.192), BigDecimal.valueOf(0.176), BigDecimal.valueOf(0.16), BigDecimal.valueOf(0.152), BigDecimal.valueOf(0.144), BigDecimal.valueOf(0.14), BigDecimal.valueOf(0.136), BigDecimal.valueOf(0.132), BigDecimal.valueOf(0.128), BigDecimal.valueOf(0.124), BigDecimal.valueOf(0.12), BigDecimal.valueOf(0.116), BigDecimal.valueOf(0.112), BigDecimal.valueOf(0.108), BigDecimal.valueOf(0.104), BigDecimal.valueOf(0.1), BigDecimal.valueOf(0.096), BigDecimal.valueOf(0.092), BigDecimal.valueOf(0.088), BigDecimal.valueOf(0.084), BigDecimal.valueOf(0.08), BigDecimal.valueOf(0.076), BigDecimal.valueOf(0.072), BigDecimal.valueOf(0.068), BigDecimal.valueOf(0.064), BigDecimal.valueOf(0.06), BigDecimal.valueOf(0.056), BigDecimal.valueOf(0.052), BigDecimal.valueOf(0.048), BigDecimal.valueOf(0.044), BigDecimal.valueOf(0.04), BigDecimal.valueOf(0.036), BigDecimal.valueOf(0.032), BigDecimal.valueOf(0.028), BigDecimal.valueOf(0.024), BigDecimal.valueOf(0.02), BigDecimal.valueOf(0.016), BigDecimal.valueOf(0.012), BigDecimal.valueOf(0.008), BigDecimal.valueOf(0.004), BigDecimal.valueOf(0)]
const TAB5: any = [BigDecimal.ZERO, BigDecimal.valueOf(1900), BigDecimal.valueOf(1824), BigDecimal.valueOf(1748), BigDecimal.valueOf(1672), BigDecimal.valueOf(1596), BigDecimal.valueOf(1520), BigDecimal.valueOf(1444), BigDecimal.valueOf(1368), BigDecimal.valueOf(1292), BigDecimal.valueOf(1216), BigDecimal.valueOf(1140), BigDecimal.valueOf(1064), BigDecimal.valueOf(988), BigDecimal.valueOf(912), BigDecimal.valueOf(836), BigDecimal.valueOf(760), BigDecimal.valueOf(722), BigDecimal.valueOf(684), BigDecimal.valueOf(665), BigDecimal.valueOf(646), BigDecimal.valueOf(627), BigDecimal.valueOf(608), BigDecimal.valueOf(589), BigDecimal.valueOf(570), BigDecimal.valueOf(551), BigDecimal.valueOf(532), BigDecimal.valueOf(513), BigDecimal.valueOf(494), BigDecimal.valueOf(475), BigDecimal.valueOf(456), BigDecimal.valueOf(437), BigDecimal.valueOf(418), BigDecimal.valueOf(399), BigDecimal.valueOf(380), BigDecimal.valueOf(361), BigDecimal.valueOf(342), BigDecimal.valueOf(323), BigDecimal.valueOf(304), BigDecimal.valueOf(285), BigDecimal.valueOf(266), BigDecimal.valueOf(247), BigDecimal.valueOf(228), BigDecimal.valueOf(209), BigDecimal.valueOf(190), BigDecimal.valueOf(171), BigDecimal.valueOf(152), BigDecimal.valueOf(133), BigDecimal.valueOf(114), BigDecimal.valueOf(95), BigDecimal.valueOf(76), BigDecimal.valueOf(57), BigDecimal.valueOf(38), BigDecimal.valueOf(19), BigDecimal.valueOf(0)]
const ZAHL1: any = BigDecimal.ONE
const ZAHL2: any = BigDecimal.valueOf(2)
const ZAHL5: any = BigDecimal.valueOf(5)
const ZAHL7: any = BigDecimal.valueOf(7)
const ZAHL12: any = BigDecimal.valueOf(12)
const ZAHL100: any = BigDecimal.valueOf(100)
const ZAHL360: any = BigDecimal.valueOf(360)
const ZAHL500: any = BigDecimal.valueOf(500)
const ZAHL700: any = BigDecimal.valueOf(700)
const ZAHL1000: any = BigDecimal.valueOf(1000)
const ZAHL10000: any = BigDecimal.valueOf(10000)

export interface Lohnsteuer2026Input {
  af?: number
  AJAHR?: number
  ALTER1?: number
  ALV?: number
  f?: number
  JFREIB?: number | string
  JHINZU?: number | string
  JRE4?: number | string
  JRE4ENT?: number | string
  JVBEZ?: number | string
  KRV?: number
  KVZ?: number | string
  LZZ?: number
  LZZFREIB?: number | string
  LZZHINZU?: number | string
  MBV?: number | string
  PKPV?: number | string
  PKPVAGZ?: number | string
  PKV?: number
  PVA?: number | string
  PVS?: number
  PVZ?: number
  R?: number
  RE4?: number | string
  SONSTB?: number | string
  SONSTENT?: number | string
  STERBE?: number | string
  STKL?: number
  VBEZ?: number | string
  VBEZM?: number | string
  VBEZS?: number | string
  VBS?: number | string
  VJAHR?: number
  ZKF?: number | string
  ZMVB?: number
}
export interface Lohnsteuer2026Output {
  BK: BigDecimal
  BKS: BigDecimal
  LSTLZZ: BigDecimal
  SOLZLZZ: BigDecimal
  SOLZS: BigDecimal
  STS: BigDecimal
  VFRB: BigDecimal
  VFRBS1: BigDecimal
  VFRBS2: BigDecimal
  WVFRB: BigDecimal
  WVFRBO: BigDecimal
  WVFRBM: BigDecimal
}

/* BigDecimal inputs are in the PAP's own units: RE4 & co. in cent, KVZ in percent */
export function lohnsteuer2026(input: Lohnsteuer2026Input): Lohnsteuer2026Output {
  let af: any = 1
  let AJAHR: any = 0
  let ALTER1: any = 0
  let ALV: any = 0
  let f: any = 1.0
  let JFREIB: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let JHINZU: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let JRE4: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let JRE4ENT: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let JVBEZ: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let KRV: any = 0
  let KVZ: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let LZZ: any = 1
  let LZZFREIB: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let LZZHINZU: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let MBV: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let PKPV: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let PKPVAGZ: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let PKV: any = 0
  let PVA: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let PVS: any = 0
  let PVZ: any = 0
  let R: any = 0
  let RE4: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let SONSTB: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let SONSTENT: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let STERBE: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let STKL: any = 1
  let VBEZ: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VBEZM: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VBEZS: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VBS: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VJAHR: any = 0
  let ZKF: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ZMVB: any = 0
  let BK: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let BKS: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let LSTLZZ: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let SOLZLZZ: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let SOLZS: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let STS: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VFRB: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VFRBS1: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VFRBS2: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let WVFRB: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let WVFRBO: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let WVFRBM: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ALTE: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ANP: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ANTEIL1: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let AVSATZAN: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let BBGKVPV: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let BBGRVALV: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let BMG: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let DIFF: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let EFA: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let FVB: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let FVBSO: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let FVBZ: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let FVBZSO: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let GFB: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let HBALTE: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let HFVB: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let HFVBZ: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let HFVBZSO: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let HOCH: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let J: any = 0
  let JBMG: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let JLFREIB: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let JLHINZU: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let JW: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let K: any = 0
  let KFB: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let KVSATZAN: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let KZTAB: any = 0
  let LSTJAHR: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let LSTOSO: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let LSTSO: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let MIST: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let PKPVAGZJ: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let PVSATZAN: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let RVSATZAN: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let RW: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let SAP: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let SOLZFREI: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let SOLZJ: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let SOLZMIN: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let SOLZSBMG: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let SOLZSZVE: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ST: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ST1: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ST2: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VBEZB: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VBEZBSO: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VERGL: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VSPHB: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VSP: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VSPN: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VSPALV: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VSPKVPV: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let VSPR: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let W1STKL5: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let W2STKL5: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let W3STKL5: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let X: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let Y: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ZRE4: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ZRE4J: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ZRE4VP: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ZRE4VPR: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ZTABFB: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ZVBEZ: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ZVBEZJ: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ZVE: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ZX: any = BigDecimal.valueOf(BigDecimal.ZERO)
  let ZZX: any = BigDecimal.valueOf(BigDecimal.ZERO)
  if (input.af !== undefined) af = input.af
  if (input.AJAHR !== undefined) AJAHR = input.AJAHR
  if (input.ALTER1 !== undefined) ALTER1 = input.ALTER1
  if (input.ALV !== undefined) ALV = input.ALV
  if (input.f !== undefined) f = input.f
  if (input.JFREIB !== undefined) JFREIB = BigDecimal.valueOf(input.JFREIB)
  if (input.JHINZU !== undefined) JHINZU = BigDecimal.valueOf(input.JHINZU)
  if (input.JRE4 !== undefined) JRE4 = BigDecimal.valueOf(input.JRE4)
  if (input.JRE4ENT !== undefined) JRE4ENT = BigDecimal.valueOf(input.JRE4ENT)
  if (input.JVBEZ !== undefined) JVBEZ = BigDecimal.valueOf(input.JVBEZ)
  if (input.KRV !== undefined) KRV = input.KRV
  if (input.KVZ !== undefined) KVZ = BigDecimal.valueOf(input.KVZ)
  if (input.LZZ !== undefined) LZZ = input.LZZ
  if (input.LZZFREIB !== undefined) LZZFREIB = BigDecimal.valueOf(input.LZZFREIB)
  if (input.LZZHINZU !== undefined) LZZHINZU = BigDecimal.valueOf(input.LZZHINZU)
  if (input.MBV !== undefined) MBV = BigDecimal.valueOf(input.MBV)
  if (input.PKPV !== undefined) PKPV = BigDecimal.valueOf(input.PKPV)
  if (input.PKPVAGZ !== undefined) PKPVAGZ = BigDecimal.valueOf(input.PKPVAGZ)
  if (input.PKV !== undefined) PKV = input.PKV
  if (input.PVA !== undefined) PVA = BigDecimal.valueOf(input.PVA)
  if (input.PVS !== undefined) PVS = input.PVS
  if (input.PVZ !== undefined) PVZ = input.PVZ
  if (input.R !== undefined) R = input.R
  if (input.RE4 !== undefined) RE4 = BigDecimal.valueOf(input.RE4)
  if (input.SONSTB !== undefined) SONSTB = BigDecimal.valueOf(input.SONSTB)
  if (input.SONSTENT !== undefined) SONSTENT = BigDecimal.valueOf(input.SONSTENT)
  if (input.STERBE !== undefined) STERBE = BigDecimal.valueOf(input.STERBE)
  if (input.STKL !== undefined) STKL = input.STKL
  if (input.VBEZ !== undefined) VBEZ = BigDecimal.valueOf(input.VBEZ)
  if (input.VBEZM !== undefined) VBEZM = BigDecimal.valueOf(input.VBEZM)
  if (input.VBEZS !== undefined) VBEZS = BigDecimal.valueOf(input.VBEZS)
  if (input.VBS !== undefined) VBS = BigDecimal.valueOf(input.VBS)
  if (input.VJAHR !== undefined) VJAHR = input.VJAHR
  if (input.ZKF !== undefined) ZKF = BigDecimal.valueOf(input.ZKF)
  if (input.ZMVB !== undefined) ZMVB = input.ZMVB
  function None() {
    MPARA();
    MRE4JL();
    VBEZBSO= BigDecimal.ZERO;
    MRE4();
    MRE4ABZ();
    MBERECH();
    MSONST();
  }
  function MPARA() {
    BBGRVALV = BigDecimal.valueOf(101400);
    AVSATZAN = BigDecimal.valueOf(0.013);
    RVSATZAN = BigDecimal.valueOf(0.093);
    BBGKVPV = BigDecimal.valueOf(69750);
    KVSATZAN =(KVZ.divide(ZAHL2).divide(ZAHL100)).add(BigDecimal.valueOf(0.07));
    if (PVS == 1) {
      PVSATZAN = BigDecimal.valueOf(0.023);
    } else {
      PVSATZAN =  BigDecimal.valueOf(0.018);
    }
    if (PVZ == 1) {
      PVSATZAN = PVSATZAN.add(BigDecimal.valueOf(0.006));
    } else {
      PVSATZAN = PVSATZAN.subtract(PVA.multiply(BigDecimal.valueOf(0.0025)));
    }
    W1STKL5 = BigDecimal.valueOf(14071);
    W2STKL5 = BigDecimal.valueOf(34939);
    W3STKL5 = BigDecimal.valueOf(222260);
    GFB = BigDecimal.valueOf(12348);
    SOLZFREI = BigDecimal.valueOf(20350);
  }
  function MRE4JL() {
    if (LZZ == 1) {
      ZRE4J= RE4.divide(ZAHL100, 2, BigDecimal.ROUND_DOWN);
      ZVBEZJ= VBEZ.divide(ZAHL100, 2, BigDecimal.ROUND_DOWN);
      JLFREIB= LZZFREIB.divide(ZAHL100, 2, BigDecimal.ROUND_DOWN);
      JLHINZU= LZZHINZU.divide(ZAHL100, 2, BigDecimal.ROUND_DOWN);
    } else {
      if (LZZ == 2) {
        ZRE4J=(RE4.multiply(ZAHL12)).divide(ZAHL100, 2, BigDecimal.ROUND_DOWN);
        ZVBEZJ=(VBEZ.multiply(ZAHL12)).divide(ZAHL100, 2, BigDecimal.ROUND_DOWN);
        JLFREIB=(LZZFREIB.multiply(ZAHL12)).divide(ZAHL100, 2, BigDecimal.ROUND_DOWN);
        JLHINZU=(LZZHINZU.multiply(ZAHL12)).divide(ZAHL100, 2, BigDecimal.ROUND_DOWN);
      } else {
        if (LZZ == 3) {
          ZRE4J=(RE4.multiply(ZAHL360)).divide(ZAHL700, 2, BigDecimal.ROUND_DOWN);
          ZVBEZJ=(VBEZ.multiply(ZAHL360)).divide(ZAHL700, 2, BigDecimal.ROUND_DOWN);
          JLFREIB=(LZZFREIB.multiply(ZAHL360)).divide(ZAHL700, 2, BigDecimal.ROUND_DOWN);
          JLHINZU=(LZZHINZU.multiply(ZAHL360)).divide(ZAHL700, 2, BigDecimal.ROUND_DOWN);
        } else {
          ZRE4J=(RE4.multiply(ZAHL360)).divide(ZAHL100, 2, BigDecimal.ROUND_DOWN);
          ZVBEZJ=(VBEZ.multiply(ZAHL360)).divide(ZAHL100, 2, BigDecimal.ROUND_DOWN);
          JLFREIB=(LZZFREIB.multiply(ZAHL360)).divide(ZAHL100, 2, BigDecimal.ROUND_DOWN);
          JLHINZU=(LZZHINZU.multiply(ZAHL360)).divide(ZAHL100, 2, BigDecimal.ROUND_DOWN);
        }
      }
    }
    if (af == 0) {
      f= 1;
    }
  }
  function MRE4() {
    if (ZVBEZJ.compareTo(BigDecimal.ZERO) == 0) {
      FVBZ= BigDecimal.ZERO;
      FVB= BigDecimal.ZERO;
      FVBZSO= BigDecimal.ZERO;
      FVBSO= BigDecimal.ZERO;
    } else {
      if (VJAHR < 2006) {
        J= 1;
      } else {
        if (VJAHR < 2058) {
          J= VJAHR - 2004;
        } else {
          J= 54;
        }
      }
      if (LZZ == 1) {
        VBEZB=(VBEZM.multiply(BigDecimal.valueOf(ZMVB))).add(VBEZS);
        HFVB= TAB2[J].divide(ZAHL12).multiply(BigDecimal.valueOf(ZMVB)).setScale(0, BigDecimal.ROUND_UP);
        FVBZ= TAB3[J].divide(ZAHL12).multiply(BigDecimal.valueOf(ZMVB)).setScale(0, BigDecimal.ROUND_UP);
      } else {
        VBEZB=((VBEZM.multiply(ZAHL12)).add(VBEZS)).setScale(2, BigDecimal.ROUND_DOWN);
        HFVB= TAB2[J];
        FVBZ= TAB3[J];
      }
      FVB=((VBEZB.multiply(TAB1[J]))).divide(ZAHL100).setScale(2, BigDecimal.ROUND_UP);
      if (FVB.compareTo(HFVB) == 1) {
        FVB = HFVB;
      }
      if (FVB.compareTo(ZVBEZJ) == 1) {
        FVB = ZVBEZJ;
      }
      FVBSO=(FVB.add((VBEZBSO.multiply(TAB1[J])).divide(ZAHL100))).setScale(2, BigDecimal.ROUND_UP);
      if (FVBSO.compareTo(TAB2[J]) == 1) {
        FVBSO = TAB2[J];
      }
      HFVBZSO=(((VBEZB.add(VBEZBSO)).divide(ZAHL100)).subtract(FVBSO)).setScale(2, BigDecimal.ROUND_DOWN);
      FVBZSO=(FVBZ.add((VBEZBSO).divide(ZAHL100))).setScale(0, BigDecimal.ROUND_UP);
      if (FVBZSO.compareTo(HFVBZSO) == 1) {
        FVBZSO = HFVBZSO.setScale(0, BigDecimal.ROUND_UP);
      }
      if (FVBZSO.compareTo(TAB3[J]) == 1) {
        FVBZSO = TAB3[J];
      }
      HFVBZ=((VBEZB.divide(ZAHL100)).subtract(FVB)).setScale(2, BigDecimal.ROUND_DOWN);
      if (FVBZ.compareTo(HFVBZ) == 1) {
        FVBZ = HFVBZ.setScale(0, BigDecimal.ROUND_UP);
      }
    }
    MRE4ALTE();
  }
  function MRE4ALTE() {
    if (ALTER1 == 0) {
      ALTE= BigDecimal.ZERO;
    } else {
      if (AJAHR < 2006) {
        K= 1;
      } else {
        if (AJAHR < 2058) {
          K= AJAHR - 2004;
        } else {
          K= 54;
        }
      }
      BMG= ZRE4J.subtract(ZVBEZJ);
      ALTE =(BMG.multiply(TAB4[K])).setScale(0, BigDecimal.ROUND_UP);
      HBALTE= TAB5[K];
      if (ALTE.compareTo(HBALTE) == 1) {
        ALTE= HBALTE;
      }
    }
  }
  function MRE4ABZ() {
    ZRE4=(ZRE4J.subtract(FVB).subtract(ALTE).subtract(JLFREIB).add(JLHINZU)).setScale(2, BigDecimal.ROUND_DOWN);
    if (ZRE4.compareTo(BigDecimal.ZERO) == -1) {
      ZRE4= BigDecimal.ZERO;
    }
    ZRE4VP= ZRE4J;
    ZVBEZ = ZVBEZJ.subtract(FVB).setScale(2, BigDecimal.ROUND_DOWN);
    if (ZVBEZ.compareTo(BigDecimal.ZERO) == -1) {
      ZVBEZ = BigDecimal.ZERO;
    }
  }
  function MBERECH() {
    MZTABFB();
    VFRB =((ANP.add(FVB.add(FVBZ))).multiply(ZAHL100)).setScale(0, BigDecimal.ROUND_DOWN);
    MLSTJAHR();
    WVFRB =((ZVE.subtract(GFB)).multiply(ZAHL100)).setScale(0, BigDecimal.ROUND_DOWN);
    if (WVFRB.compareTo(BigDecimal.ZERO) == -1) {
      WVFRB = BigDecimal.ZERO;
    }
    LSTJAHR =(ST.multiply(BigDecimal.valueOf(f))).setScale(0,BigDecimal.ROUND_DOWN);
    UPLSTLZZ();
    if (ZKF.compareTo(BigDecimal.ZERO) == 1) {
      ZTABFB = ZTABFB.add(KFB);
      MRE4ABZ();
      MLSTJAHR();
      JBMG =(ST.multiply(BigDecimal.valueOf(f))).setScale(0,BigDecimal.ROUND_DOWN);
    } else {
      JBMG = LSTJAHR;
    }
    MSOLZ();
  }
  function MZTABFB() {
    ANP= BigDecimal.ZERO;
    if (ZVBEZ.compareTo(BigDecimal.ZERO) >= 0 && ZVBEZ.compareTo(FVBZ) == -1) {
      FVBZ = BigDecimal.valueOf(ZVBEZ.longValue());
    }
    if (STKL < 6) {
      if (ZVBEZ.compareTo(BigDecimal.ZERO) == 1) {
        if ((ZVBEZ.subtract(FVBZ)).compareTo(BigDecimal.valueOf(102)) == -1) {
          ANP=(ZVBEZ.subtract(FVBZ)).setScale(0, BigDecimal.ROUND_UP);
        } else {
          ANP= BigDecimal.valueOf(102);
        }
      }
    } else {
      FVBZ= BigDecimal.ZERO;
      FVBZSO= BigDecimal.ZERO;
    }
    if (STKL < 6) {
      if (ZRE4.compareTo(ZVBEZ) == 1) {
        if (ZRE4.subtract(ZVBEZ).compareTo(BigDecimal.valueOf(1230)) == -1) {
          ANP = ANP.add(ZRE4).subtract(ZVBEZ).setScale(0,BigDecimal.ROUND_UP);
        } else {
          ANP = ANP.add(BigDecimal.valueOf(1230));
        }
      }
    }
    KZTAB= 1;
    if (STKL == 1) {
      SAP= BigDecimal.valueOf(36);
      KFB=(ZKF.multiply(BigDecimal.valueOf(9756))).setScale(0, BigDecimal.ROUND_DOWN);
    } else {
      if (STKL == 2) {
        EFA= BigDecimal.valueOf(4260);
        SAP= BigDecimal.valueOf(36);
        KFB=(ZKF.multiply(BigDecimal.valueOf(9756))).setScale(0, BigDecimal.ROUND_DOWN);
      } else {
        if (STKL == 3) {
          KZTAB= 2;
          SAP= BigDecimal.valueOf(36);
          KFB=(ZKF.multiply(BigDecimal.valueOf(9756))).setScale(0, BigDecimal.ROUND_DOWN);
        } else {
          if (STKL == 4) {
            SAP= BigDecimal.valueOf(36);
            KFB=(ZKF.multiply(BigDecimal.valueOf(4878))).setScale(0, BigDecimal.ROUND_DOWN);
          } else {
            if (STKL == 5) {
              SAP= BigDecimal.valueOf(36);
              KFB= BigDecimal.ZERO;
            } else {
              KFB= BigDecimal.ZERO;
            }
          }
        }
      }
    }
    ZTABFB=(EFA.add(ANP).add(SAP).add(FVBZ)).setScale(2, BigDecimal.ROUND_DOWN);
  }
  function MLSTJAHR() {
    UPEVP();
    ZVE= ZRE4.subtract(ZTABFB).subtract(VSP);
    UPMLST();
  }
  function UPLSTLZZ() {
    JW = LSTJAHR.multiply(ZAHL100);
    UPANTEIL();
    LSTLZZ = ANTEIL1;
  }
  function UPMLST() {
    if (ZVE.compareTo(ZAHL1) == -1) {
      ZVE= BigDecimal.ZERO;
      X= BigDecimal.ZERO;
    } else {
      X=(ZVE.divide(BigDecimal.valueOf(KZTAB))).setScale(0, BigDecimal.ROUND_DOWN);
    }
    if (STKL < 5) {
      UPTAB26();
    } else {
      MST5_6();
    }
  }
  function UPEVP() {
    if (KRV == 1) {
      VSPR = BigDecimal.ZERO;
    } else {
      if (ZRE4VP.compareTo(BBGRVALV) == 1) {
        ZRE4VPR = BBGRVALV;
      } else {
        ZRE4VPR = ZRE4VP;
      }
      VSPR =(ZRE4VPR.multiply(RVSATZAN)).setScale(2,BigDecimal.ROUND_DOWN);
    }
    MVSPKVPV();
    if (ALV == 1) {
    } else {
      if (STKL == 6) {
      } else {
        MVSPHB();
      }
    }
  }
  function MVSPKVPV() {
    if (ZRE4VP.compareTo(BBGKVPV) == 1) {
      ZRE4VPR = BBGKVPV;
    } else {
      ZRE4VPR = ZRE4VP;
    }
    if (PKV > 0) {
      if (STKL == 6) {
        VSPKVPV = BigDecimal.ZERO;
      } else {
        PKPVAGZJ = PKPVAGZ.multiply(ZAHL12).divide(ZAHL100).setScale(2,BigDecimal.ROUND_DOWN);
        VSPKVPV = PKPV.multiply(ZAHL12).divide(ZAHL100).setScale(2, BigDecimal.ROUND_DOWN);
        VSPKVPV = VSPKVPV.subtract(PKPVAGZJ);
        if (VSPKVPV.compareTo(BigDecimal.ZERO) == -1) {
          VSPKVPV = BigDecimal.ZERO;
        }
      }
    } else {
      VSPKVPV = ZRE4VPR.multiply(KVSATZAN.add(PVSATZAN)).setScale(2, BigDecimal.ROUND_DOWN);
    }
    VSP = VSPKVPV.add(VSPR).setScale(0, BigDecimal.ROUND_UP);
  }
  function MVSPHB() {
    if (ZRE4VP.compareTo(BBGRVALV) == 1) {
      ZRE4VPR = BBGRVALV;
    } else {
      ZRE4VPR = ZRE4VP;
    }
    VSPALV = AVSATZAN.multiply(ZRE4VPR).setScale(2, BigDecimal.ROUND_DOWN);
    VSPHB = VSPALV.add(VSPKVPV).setScale(2, BigDecimal.ROUND_DOWN);
    if (VSPHB.compareTo(BigDecimal.valueOf(1900)) == 1) {
      VSPHB = BigDecimal.valueOf(1900);
    }
    VSPN = VSPR.add(VSPHB).setScale(0, BigDecimal.ROUND_UP);
    if (VSPN.compareTo(VSP) == 1) {
      VSP = VSPN;
    }
  }
  function MST5_6() {
    ZZX= X;
    if (ZZX.compareTo(W2STKL5) == 1) {
      ZX= W2STKL5;
      UP5_6();
      if (ZZX.compareTo(W3STKL5) == 1) {
        ST=(ST.add((W3STKL5.subtract(W2STKL5)).multiply(BigDecimal.valueOf(0.42)))).setScale(0, BigDecimal.ROUND_DOWN);
        ST=(ST.add((ZZX.subtract(W3STKL5)).multiply(BigDecimal.valueOf(0.45)))).setScale(0, BigDecimal.ROUND_DOWN);
      } else {
        ST=(ST.add((ZZX.subtract(W2STKL5)).multiply(BigDecimal.valueOf(0.42)))).setScale(0, BigDecimal.ROUND_DOWN);
      }
    } else {
      ZX= ZZX;
      UP5_6();
      if (ZZX.compareTo(W1STKL5) == 1) {
        VERGL= ST;
        ZX= W1STKL5;
        UP5_6();
        HOCH=(ST.add((ZZX.subtract(W1STKL5)).multiply(BigDecimal.valueOf(0.42)))).setScale(0, BigDecimal.ROUND_DOWN);
        if (HOCH.compareTo(VERGL) == -1) {
          ST= HOCH;
        } else {
          ST= VERGL;
        }
      }
    }
  }
  function UP5_6() {
    X=(ZX.multiply(BigDecimal.valueOf(1.25))).setScale(0, BigDecimal.ROUND_DOWN);
    UPTAB26();
    ST1= ST;
    X=(ZX.multiply(BigDecimal.valueOf(0.75))).setScale(0, BigDecimal.ROUND_DOWN);
    UPTAB26();
    ST2= ST;
    DIFF=(ST1.subtract(ST2)).multiply(ZAHL2);
    MIST=(ZX.multiply(BigDecimal.valueOf(0.14))).setScale(0, BigDecimal.ROUND_DOWN);
    if (MIST.compareTo(DIFF) == 1) {
      ST= MIST;
    } else {
      ST= DIFF;
    }
  }
  function MSOLZ() {
    SOLZFREI =(SOLZFREI.multiply(BigDecimal.valueOf(KZTAB)));
    if (JBMG.compareTo(SOLZFREI) == 1) {
      SOLZJ=(JBMG.multiply(BigDecimal.valueOf(5.5))).divide(ZAHL100).setScale(2, BigDecimal.ROUND_DOWN);
      SOLZMIN=(JBMG.subtract(SOLZFREI)).multiply(BigDecimal.valueOf(11.9)).divide(ZAHL100).setScale(2, BigDecimal.ROUND_DOWN);
      if (SOLZMIN.compareTo(SOLZJ) == -1) {
        SOLZJ= SOLZMIN;
      }
      JW= SOLZJ.multiply(ZAHL100).setScale(0, BigDecimal.ROUND_DOWN);
      UPANTEIL();
      SOLZLZZ= ANTEIL1;
    } else {
      SOLZLZZ= BigDecimal.ZERO;
    }
    if (R > 0) {
      JW= JBMG.multiply(ZAHL100);
      UPANTEIL();
      BK= ANTEIL1;
    } else {
      BK= BigDecimal.ZERO;
    }
  }
  function UPANTEIL() {
    if (LZZ == 1) {
      ANTEIL1= JW;
    } else {
      if (LZZ == 2) {
        ANTEIL1= JW.divide(ZAHL12, 0, BigDecimal.ROUND_DOWN);
      } else {
        if (LZZ == 3) {
          ANTEIL1=(JW.multiply(ZAHL7)).divide(ZAHL360, 0, BigDecimal.ROUND_DOWN);
        } else {
          ANTEIL1= JW.divide(ZAHL360, 0, BigDecimal.ROUND_DOWN);
        }
      }
    }
  }
  function MSONST() {
    LZZ = 1;
    if (ZMVB == 0) {
      ZMVB = 12;
    }
    if (SONSTB.compareTo(BigDecimal.ZERO) == 0 && MBV.compareTo(BigDecimal.ZERO) == 0) {
      LSTSO= BigDecimal.ZERO;
      STS= BigDecimal.ZERO;
      SOLZS= BigDecimal.ZERO;
      BKS= BigDecimal.ZERO;
    } else {
      MOSONST();
      ZRE4J=((JRE4.add(SONSTB)).divide(ZAHL100)).setScale(2, BigDecimal.ROUND_DOWN);
      ZVBEZJ=((JVBEZ.add(VBS)).divide(ZAHL100)).setScale(2, BigDecimal.ROUND_DOWN);
      VBEZBSO= STERBE;
      MRE4SONST();
      MLSTJAHR();
      WVFRBM =(ZVE.subtract(GFB)).multiply(ZAHL100).setScale(2,BigDecimal.ROUND_DOWN);
      if (WVFRBM.compareTo(BigDecimal.ZERO) == -1) {
        WVFRBM = BigDecimal.ZERO;
      }
      LSTSO= ST.multiply(ZAHL100);
      STS = LSTSO.subtract(LSTOSO).multiply(BigDecimal.valueOf(f)).divide(ZAHL100, 0, BigDecimal.ROUND_DOWN).multiply(ZAHL100);
      STSMIN();
    }
  }
  function STSMIN() {
    if (STS.compareTo(BigDecimal.ZERO) == -1) {
      if (MBV.compareTo(BigDecimal.ZERO) == 0) {
      } else {
        LSTLZZ = LSTLZZ.add(STS);
        if (LSTLZZ.compareTo(BigDecimal.ZERO) == -1) {
          LSTLZZ = BigDecimal.ZERO;
        }
        SOLZLZZ = SOLZLZZ.add(STS.multiply(BigDecimal.valueOf(5.5).divide(ZAHL100))).setScale(0, BigDecimal.ROUND_DOWN);
        if (SOLZLZZ.compareTo(BigDecimal.ZERO) == -1) {
          SOLZLZZ = BigDecimal.ZERO;
        }
        BK = BK.add(STS);
        if (BK.compareTo(BigDecimal.ZERO) == -1) {
          BK = BigDecimal.ZERO;
        }
      }
      STS = BigDecimal.ZERO;
      SOLZS = BigDecimal.ZERO;
    } else {
      MSOLZSTS();
    }
    if (R > 0) {
      BKS = STS;
    } else {
      BKS = BigDecimal.ZERO;
    }
  }
  function MSOLZSTS() {
    if (ZKF.compareTo(BigDecimal.ZERO) == 1) {
      SOLZSZVE= ZVE.subtract(KFB);
    } else {
      SOLZSZVE= ZVE;
    }
    if (SOLZSZVE.compareTo(BigDecimal.ONE) == -1) {
      SOLZSZVE= BigDecimal.ZERO;
      X= BigDecimal.ZERO;
    } else {
      X= SOLZSZVE.divide(BigDecimal.valueOf(KZTAB), 0, BigDecimal.ROUND_DOWN);
    }
    if (STKL < 5) {
      UPTAB26();
    } else {
      MST5_6();
    }
    SOLZSBMG= ST.multiply(BigDecimal.valueOf(f)).setScale(0,BigDecimal.ROUND_DOWN);
    if (SOLZSBMG.compareTo(SOLZFREI) == 1) {
      SOLZS= STS.multiply(BigDecimal.valueOf(5.5)).divide(ZAHL100, 0, BigDecimal.ROUND_DOWN);
    } else {
      SOLZS= BigDecimal.ZERO;
    }
  }
  function MOSONST() {
    ZRE4J=(JRE4.divide(ZAHL100)).setScale(2, BigDecimal.ROUND_DOWN);
    ZVBEZJ=(JVBEZ.divide(ZAHL100)).setScale(2, BigDecimal.ROUND_DOWN);
    JLFREIB= JFREIB.divide(ZAHL100, 2, BigDecimal.ROUND_DOWN);
    JLHINZU= JHINZU.divide(ZAHL100, 2, BigDecimal.ROUND_DOWN);
    MRE4();
    MRE4ABZ();
    ZRE4VP = ZRE4VP.subtract(JRE4ENT.divide(ZAHL100));
    MZTABFB();
    VFRBS1 =((ANP.add(FVB.add(FVBZ))).multiply(ZAHL100)).setScale(2,BigDecimal.ROUND_DOWN);
    MLSTJAHR();
    WVFRBO =((ZVE.subtract(GFB)).multiply(ZAHL100)).setScale(2, BigDecimal.ROUND_DOWN);
    if (WVFRBO.compareTo(BigDecimal.ZERO) == -1) {
      WVFRBO = BigDecimal.ZERO;
    }
    LSTOSO= ST.multiply(ZAHL100);
  }
  function MRE4SONST() {
    MRE4();
    FVB= FVBSO;
    MRE4ABZ();
    ZRE4VP = ZRE4VP.add(MBV.divide(ZAHL100)).subtract(JRE4ENT.divide(ZAHL100)).subtract(SONSTENT.divide(ZAHL100));
    FVBZ= FVBZSO;
    MZTABFB();
    VFRBS2 =((((ANP.add(FVB).add(FVBZ))).multiply(ZAHL100))).subtract(VFRBS1);
  }
  function UPTAB26() {
    if (X.compareTo(GFB.add(ZAHL1)) == -1) {
      ST= BigDecimal.ZERO;
    } else {
      if (X.compareTo(BigDecimal.valueOf(17800)) == -1) {
        Y =(X.subtract(GFB)).divide(ZAHL10000, 6,BigDecimal.ROUND_DOWN);
        RW= Y.multiply(BigDecimal.valueOf(914.51));
        RW= RW.add(BigDecimal.valueOf(1400));
        ST=(RW.multiply(Y)).setScale(0, BigDecimal.ROUND_DOWN);
      } else {
        if (X.compareTo(BigDecimal.valueOf(69879)) == -1) {
          Y=(X.subtract(BigDecimal.valueOf(17799))).divide(ZAHL10000, 6, BigDecimal.ROUND_DOWN);
          RW= Y.multiply(BigDecimal.valueOf(173.1));
          RW= RW.add(BigDecimal.valueOf(2397));
          RW= RW.multiply(Y);
          ST=(RW.add(BigDecimal.valueOf(1034.87))).setScale(0, BigDecimal.ROUND_DOWN);
        } else {
          if (X.compareTo(BigDecimal.valueOf(277826)) == -1) {
            ST=((X.multiply(BigDecimal.valueOf(0.42))).subtract(BigDecimal.valueOf(11135.63))).setScale(0, BigDecimal.ROUND_DOWN);
          } else {
            ST=((X.multiply(BigDecimal.valueOf(0.45))).subtract(BigDecimal.valueOf(19470.38))).setScale(0, BigDecimal.ROUND_DOWN);
          }
        }
      }
    }
    ST= ST.multiply(BigDecimal.valueOf(KZTAB));
  }
  MPARA();
  MRE4JL();
  VBEZBSO= BigDecimal.ZERO;
  MRE4();
  MRE4ABZ();
  MBERECH();
  MSONST();
  return { BK, BKS, LSTLZZ, SOLZLZZ, SOLZS, STS, VFRB, VFRBS1, VFRBS2, WVFRB, WVFRBO, WVFRBM }
}
