#!/bin/sh
# Packs src/lib/tax/estimate.ts (and the generated payroll-tax plan it calls) into one
# script the iPhone app runs in JavaScriptCore (TaxEngine.swift), so both apps compute
# with the very same code. Re-run after changing anything under src/lib/tax.
set -e
cd "$(dirname "$0")/.."
npx esbuild src/lib/tax/estimate.ts --bundle --format=iife --global-name=SplitlifeTax --target=es2020 \
  --banner:js="// generated by scripts/bundle-tax.sh from src/lib/tax — do not edit" \
  --outfile=ios-native/Heimat/tax.js --log-level=warning
