#!/usr/bin/env python3
"""Turns the Finance Ministry's payroll-tax plan (PAP) — published as pseudo-code in XML at
https://www.bmf-steuerrechner.de (Lohnsteuer<year>.xml) — into TypeScript, mechanically,
so not one line of the tax rules is typed by hand. The statements are Java on BigDecimal;
src/lib/tax/bigdec.ts gives them the same arithmetic.

  python3 scripts/gen-lohnsteuer.py src/lib/tax/Lohnsteuer2026.xml src/lib/tax/lohnsteuer2026.gen.ts
"""
import sys, re, hashlib
import xml.etree.ElementTree as ET

src, out = sys.argv[1], sys.argv[2]
raw = open(src, 'rb').read()
root = ET.fromstring(raw.decode('utf-8-sig'))
name = root.get('name')

def j(expr: str) -> str:
    e = expr.strip()
    e = re.sub(r'\s*\(\s*', '(', e)           # "X.compareTo (Y)" → "X.compareTo(Y)"
    e = e.replace('{', '[').replace('}', ']')  # array literals
    return e

decls, inputs, outputs = [], [], []
for v in root.find('VARIABLES'):
    for el in v:
        if el.tag not in ('INPUT', 'OUTPUT', 'INTERNAL'): continue
        n, t = el.get('name'), el.get('type')
        default = el.get('default')
        if t == 'BigDecimal':
            init = 'BigDecimal.ZERO' if default is None else f'BigDecimal.valueOf({default})'
        elif t in ('int', 'double'):
            init = default if default is not None else '0'
        else:
            raise SystemExit(f'unknown type {t} for {n}')
        decls.append(f'  let {n}: any = {init}')
        (inputs if el.tag == 'INPUT' else outputs if el.tag == 'OUTPUT' else []).append((n, t))
consts = []
for c in root.find('CONSTANTS'):
    consts.append(f'const {c.get("name")}: any = {j(c.get("value"))}')

def body(node, ind):
    lines = []
    for el in node:
        if el.tag == 'EVAL':
            lines.append(f'{ind}{j(el.get("exec"))};')
        elif el.tag == 'EXECUTE':
            lines.append(f'{ind}{el.get("method")}();')
        elif el.tag == 'IF':
            lines.append(f'{ind}if ({j(el.get("expr"))}) {{')
            th, el_ = el.find('THEN'), el.find('ELSE')
            if th is not None: lines += body(th, ind + '  ')
            if el_ is not None:
                lines.append(f'{ind}}} else {{')
                lines += body(el_, ind + '  ')
            lines.append(f'{ind}}}')
        else:
            raise SystemExit(f'unknown statement {el.tag}')
    return lines

methods = []
for m in root.find('METHODS'):
    methods.append(f'  function {m.get("name")}() {{')
    methods += body(m, '    ')
    methods.append('  }')
main = body(root.find('METHODS').find('MAIN') if root.find('METHODS').find('MAIN') is not None else root.find('MAIN'), '  ')

in_t = '\n'.join(f'  {n}?: {"number" if t != "BigDecimal" else "number | string"}' for n, t in inputs)
out_t = '\n'.join(f'  {n}: BigDecimal' for n, _ in outputs)
assign = '\n'.join(f'  if (input.{n} !== undefined) {n} = {"BigDecimal.valueOf(input." + n + ")" if t == "BigDecimal" else "input." + n}' for n, t in inputs)
ret = ', '.join(f'{n}' for n, _ in outputs)
bigdec = open(__import__('os').path.join(__import__('os').path.dirname(out), 'bigdec.ts')).read()
code = f'''// @ts-nocheck — generated by scripts/gen-lohnsteuer.py from {src.split("/")[-1]} (md5 {hashlib.md5(raw).hexdigest()}); do not edit
// The German payroll tax plan ({name}) exactly as the Finance Ministry publishes it.
{bigdec}

{chr(10).join(consts)}

export interface {name}Input {{
{in_t}
}}
export interface {name}Output {{
{out_t}
}}

/* BigDecimal inputs are in the PAP's own units: RE4 & co. in cent, KVZ in percent */
export function {name.lower()}(input: {name}Input): {name}Output {{
{chr(10).join(decls)}
{assign}
{chr(10).join(methods)}
{chr(10).join(main)}
  return {{ {ret} }}
}}
'''
open(out, 'w').write(code)
print(f'{out}: {len(methods)} lines of methods, {len(inputs)} inputs, {len(outputs)} outputs')
