#!/bin/sh
# Prepares the native SwiftUI iOS app in ios-native/:
#  1. copies the Supabase URL and anon key from .env into a git-ignored Swift file
#     (the same values the web build compiles in), and
#  2. generates ios-native/Heimat.xcodeproj with xcodegen.
set -e
cd "$(dirname "$0")/.."

val() { grep "^$1=" .env | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'"; }
url=$(val VITE_SUPABASE_URL)
key=$(val VITE_SUPABASE_ANON_KEY)
pub=$(val VITE_PUBLIC_URL)
[ -z "$url" ] || [ -z "$key" ] && { echo "VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY missing in .env" >&2; exit 1; }
[ -z "$pub" ] && pub="https://meet-p-dev.github.io/Heimat/"

mkdir -p ios-native/Heimat/Generated
cat > ios-native/Heimat/Generated/Secrets.swift <<EOF
// Generated by scripts/native-ios.sh from .env — do not edit, do not commit.
enum Secrets {
    static let supabaseURL = "$url"
    static let supabaseKey = "$key"
    static let publicURL = "$pub"
}
EOF

cd ios-native && xcodegen generate --quiet
echo "ios-native/Heimat.xcodeproj ready"
